### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by xqtr** [blocktronics/moebius#101]
First of all... bravo! for this awesome ansi editor! Below are some features i would like to see in the future :)

- TheDraw Fonts support (use, edit, create etc.)
- Pressing F, display a popup menu, with choices to fill foreground color, bg color, fg and bg color, character, character and attribute.
- Copy/Paste between instances of Moebius, with full color... not it only copies the text
- The rectangle tool, fills the area, but the circle tool only draws an outline... what about a rectangle outline tool and a circle fill tool? :)
- The mouse cursor sometimes is hard to see... :(
- No need to save SAUCE record to every file, even if they don't have one. It's messing with old utils/programs that don't support SAUCE and it's annoying removing it, every time you edit the file.
- Instead of beginning with a 80x25 canvas and adding more lines (resize) every time you need more, it would be nicer to begin with a large canvas and if the user wants, crop it at the end.
- The Attribute Selector (ESC) should also work with mouse. If you work with the mouse and press ESC you have to go back to the keyboard.
- The F11 key, conflicts with the full screen mode and drawing the F11 char.
- Support of Layers and a new file type to save them. Layer support should also have the functions to export a layer or import an ansi image as a layer.
- Clipart... or just the function to import an ansi file to the working area, as a selection, with out destroying the current working area.
- A popup box/window to select the drawing chars. set. Pressing/Cycling with CTRL + , or . is not always practical, specially for noobs like me :)

I'll stop here... cause you will hate me :) I am only proposing all these, because i like Moebius :)

**Comment by christianvozar** [comment]
Some of these features are possible and need to be broken off to separate issues to have discourse on their implementation. Others are simply not doable or won't be done.

Those not being done:
- The Draw fonts.

The reasoning on this one is that they serve no purpose. I have never in the history of ansi seen a The Draw font that didn't look like open-ass when used. I understand that not all BBS sysops have the skill to draw a font and wish they could just use a generator to make one. We file this under the same category as a gif2ans program in that it provides a net-detriment to the ansi scene rather than enhancing it. There are a great many fonts that artists have provided on 16colo.rs to be used with a simple copy/paste. If the desire is simply to open a font and see its contents then I do think there is historical merit in this but that functionality doesn't belong in Moebius.

- No need to save Sauce record

I disagree with this point. A great deal of rendering information is stored in SAUCE that otherwise leads to a mess when attempting to define what the artist intended. Take a look at 16colo.rs and note that all ansi prior to a certain year (1997?) is in legacy display while after you need to be explicit. This is because prior to SAUCE we had no way to know what the artist intended so we make guesses. It's easier to new artists to automatically save SAUCE and ensure intention is saved with it. If providing a simple CLI tool that strips sauce from files is desired that is something we could provide independent of Moebius.

- Beginning the canvas at 80x25

The larger the canvas size the more resources it takes, this allows an artist to start with a standard sized screen and utilize a minimum of resources allowing them to opt-in to a larger canvas and this is by design. The preferences allows setting the size of new documents and that is the best compromise for this request.
