### ISSUE TITLE
Implement Larger Cursor

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#115]
Per @xqtr it was pointed out that the cursor can be difficult to see.

**Comment by christianvozar** [comment]
I did a side-by-side comparison of PabloDraw and Moebius' cursor at 100% and they are nearly the same in rendering. How would you propose the cursor be more visible? There could be an option to utilize a full block cursor which I have observed in Terminal applications.

**Comment by andyherbert** [comment]
If you take a look at the specific circumstances where the cursor becomes least visible, it's when it's over a dark grey glyph surrounded by a light grey area, or vice versa, this is because the graphic representing the cursor computes a difference of the colour underneath it, which happens to be the same as the other grey variant. If you made the cursor larger, by which I assume you mean as tall as the actual text character then this won't help because it will completely disappear. You could make the case that the cursor should blink, but this option already exists in preferences (which is also larger than the default one), but I've had more than one person remark to me that blinking cursors are obnoxious. Unless anyone can clarify exactly what they would want, or even better implement it in code, then I'll close this.

**Comment by bart-d** [comment]
I actually have been experimenting with the cursor before, not with the size, because that makes little sense to me. I wanted to use a full block but indeed this becomes invisible on some colors, which is probably the reason why online the outline was used for the current (flashing) cursor. I got the best results so far with CSS invert iirc, but still not very visibile on grey blocks .

Personally i like a flashing cursor (just because my old editor had this too), only that the flash frequency currently is way too fast for me, so I tend to modify that just for me :)
