### ISSUE TITLE
request to add option to leave out SAUCE info

### ISSUE THREAD

**Issue by squintgit** [blocktronics/moebius#121]
would like the option to leave out the SAUCE info from .ans files on save. this info often has to be manually stripped via a text editor after saving in Moebius in order for the ansi to look correct on a bbs.

**Comment by bart-d** [comment]
> @squintgit You can actually clear it out and update the sauce before saving the ansi file. I do this all the time whenever creating ASCII art. I usually don't add SAUCE to my ascii artwork.

that won't help tbh. it will still add a SAUCE record with eg date and font information. It's just that author/group/title and comments will be empty

**Comment by andyherbert** [comment]
I always thought this was a bad idea for a few reasons. There's always been the opposite problem that Sauce has been missing from files, Sauce also contains important metadata to display files so leaving it out could cause (destructive) changes to a file, and the onus should really be on BBS software to update their code since it's trivial to at least implement a check to ignore Sauce records. That being said I added a menu item under File to save without sauce, so it will make it marginally easier to save files this way, but hopefully avoid anyone from making a mistake.

**Comment by squintgit** [comment]
> I always thought this was a bad idea for a few reasons. There's always been the opposite problem that Sauce has been missing from files, Sauce also contains important metadata to display files so leaving it out could cause (destructive) changes to a file, and the onus should really be on BBS software to update their code since it's trivial to at least implement a check to ignore Sauce records. That being said I added a menu item under File to save without sauce, so it will make it marginally easier to save files this way, but hopefully avoid anyone from making a mistake.

Cool thanks, really nice
