### ISSUE TITLE
Blinking objects

### ISSUE THREAD

**Issue by calcmandan** [blocktronics/moebius#123]
When adding an object into colored field, for instance a dark grey field, any attempt of adding an object with a different foreground, but matching background, leads to a black background and a flashing foreground. Running 1.0.24 from 2018. Obtained the debian package off the official website about a month ago.

I made a video demonstrating this and please understand I was rather frustrated by this.
https://www.omgwtflol.net/nextcloud/index.php/s/Jw63Y7TbbMdHdWC

**Comment by bart-d** [comment]
to understand this, you need to know a little about ANSI colors. Originally you could only use all 16 colors as foreground colors and the 8 darker colors (those in the right column of the Moebius color selection) as background colors. This is a built-in limitation.

There was also a blink mode, whenever you'd set it, the foreground color would blink and the background color would remain static. And this is what you're seeing when trying to use a foreground color as a background, you're activating the blink mode. iow this is expected behavior.

However, already in the nineties some people found the limitation of just 8 background colors too limited and therefore 'reused' the blink mode to indicate that foreground color should be used as a background color. this is what we call 'iCE colors'. Terminals and applications that support iCE colors will interpret "blink mode" as high intensity background color.

You can enable "iCE colors" from the Colors menu in Moebius and your issue will magically disappear. However you should be aware of where you want to use your artwork that was created with this feature enabled, if the terminal or the application doesn't support it, it will also cause blinking.
