### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by andyherbert** [blocktronics/moebius#143]
There's a bunch of questions that always seem to come up with newcomers, and to be honest some of the questions I haven't got complete answers to, such as:

Why does my drawing blink like that?
What are ice colours and what does 9px font mean?
Why are the colours like that, and why is orange a bit funny?
What's a sauce record?

And so on... obviously most of these are wrapped up in historical accident and I think it would be a good idea to transfer a bit of knowledge if the traditions of the scene are to continue.

**Comment by bart-d** [comment]
There are indeed questions that appear to return indeed, I've done an attempt previously at making something that is understandable for novices but also provides enough technical details to explain some of these things, it's visible here: https://16colo.rs/ansiflags.php

Some things should be more elaborate, like iCE colors should have a flashing and non-flashing example to point out the effects. But I feel limited because I already have a hard time explaining things, doing it in another language only makes it worse :)

**Comment by andyherbert** [comment]
It's seems like a job for @christianvozar !

**Comment by christianvozar** [comment]
I'm ok with pushing on this but would want to keep it within the application. I'm thinking tooltips, deeper help menu system with some tutorials. 

@andyherbert Any thoughts on a tooltip library worth using? Just poking around I saw https://www.npmjs.com/package/electron-tooltip but no idea which is a quality library.

**Comment by andyherbert** [comment]
I'm not talking about tooltips, I was referring to something @bart-d has linked to, with detailed descriptions of the various terms used in ansi art.

**Comment by christianvozar** [comment]
I don't think I'm the right person for this work. I often get terms confused and looking at the 16c archive you can see I tag things with the wrong terms. I do think Lord Scarlett would be a possible candidate, though.

**Comment by andyherbert** [comment]
It's probably not going to happen if people don't volunteer. Didn't you recently do a presentation at Denver Comic Con on the culture and history of text mode art? Maybe I'm mis-remembering.
