### ISSUE TITLE
Instructions on Running a Moebius Server

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#59]
Provide wiki page on how to run a server including how to install npm on various platforms.

**Comment by andyherbert** [comment]
I'm going to spin the Moebius server out on it's own repo, and make the configuration and running as a service a bit more friendlier, I'd hold off writing anything immediately.

**Comment by tallship** [comment]
Oh geez, I just saw this issue. Maybe I jumped too soon, but the README was super fricken' ugly.

@christianvozar I don't/won't do ewboontew, but I dolled up the README a bit with cookbook style instructions for nodejs, nvm, and npm that you may appreciate, as per your request. I'm offering to break it out further too. Docs can be cut up and left with appropriate project repos as needed.

I'm missing any sort of build from source info for Windows workstation binaries though. Dunno if Andy even wants that available. 

You can view the PR in my fork containing the patch until such time as Andy decides on what to do about it, but the existing README was woefully lacking (No offense to anyone). I also left a ToDo checklist in the Documentation section and would be happy to continue supporting docs/manual if it's welcomed. 

@andyherbert , I avoided adding more complete coverage on build/deploy such as SystemD, SysV or BSD style init scripts and VirtualHost Containers or Server Blocks for Apache and Nginx, respectively, for transparent proxy in support of Moebius running under node. Also, did not cover the particulars for A, AAAA, and other RRs to support these VirtualHosts under some form of httpd.

I think a 'bit' of wiki is good, but the problem with a GitHub Wiki is that it doesn't clone or mirror (I mention this in my PR), so if I'm welcomed in beefing up docs, would be looking to do so in docs/ primarily providing links back to that from the Wiki that would contain a more spartan approach in implementing topical linkbacks to the full docs and any user manual in docs/

I can write man pages too, but dunno if this project will require something like that.

Lemme know. xqtr said he likes Moebius, and that's actually saying a lot. Me? I sucked at The Draw back in the early 90's so I'll prolly suck at using Moebius too.

**Comment by christianvozar** [comment]
@tallship Thank you for contributing. Documentation is generally the most neglected of projects so any assistance is always greatly appreciated.

I don't think we need platform-specific instructions as Node tends to run on most platforms. I do intend to provide a Docker image for the server that makes it easy to deploy to something like GCE/AWS ECS and maybe associated scripts/Makefile but that will happen during the holidays.

I don't think a man page will be necessary for this project. I think, if they aren't provided already, the only really useful output would be command-line flags via `--help` which is pretty normative for those accustomed to CLI apps.

My 2c on "to do" items is to keep them as issues on Github rather than in README so they can be tied to particular pull requests/branches.

I'll leave it to @andyherbert for merging your documentation update.

**Comment by tallship** [comment]
> I don't think we need platform-specific instructions as Node tends to run on most platforms. I do intend to provide a Docker image for the server that makes it easy to deploy to something like GCE/AWS ECS and maybe associated scripts/Makefile but that will happen during the holidays.
>

Yes I do try to avoid a lot of platform specific items, especially being a Slackware person, as such would be completely foreign to many, but in accommodating deps and such needed a baseline from which someone could reference an install, so gleaning that there was a leaning towards Debian, chose that in examples for cookbook style instructions :)
 
> I don't think a man page will be necessary for this project. I think, if they aren't provided already, the only really useful output would be command-line flags via `--help` which is pretty normative for those accustomed to CLI apps.

I agree, and especially considering there isn't much to cover there I think the `--help` flag is probably the best methodology as the product matures.
> 
> My 2c on "to do" items is to keep them as issues on Github rather than in README so they can be tied to particular pull requests/branches.
> 

Ah, yes. That resulted from my notion of a semblance for some sort of imaginary base template style. I was thinking about whether to leave that section out completely, or since I would usually put links to other, more specific docs there residing in docs/, to use it as a place holder until such time as the project devs could decide on just how to proceed (i.e., Wiki vs docs/, etc.). I got a little carried away there too IMO  ;)

Thank you for your kind words and I'll be happy to assist any way I can, but I think that after all is said and done, my prowess as an ANSI or RIP artist will still remain woefully lacking.
