### ISSUE TITLE
Feature: Custom Palatte/8-bit colors

### ISSUE THREAD

**Issue by Zuzuesque** [blocktronics/moebius#79]
I am not sure if this request goes against the spirit of moebius (or ascii art in general)--but I wondered if it was possible to support (as an option) a 8-bit palatte?

I am currently trying to use moebius to make art assets for a small Mush game, and most MU* clients support 256 colors--so it would be nice to be able and utilize that. Especially when binary export is supported for the palatte.

**Comment by andyherbert** [comment]
There's quite a few competing implementations above the standard EGA palette in ANSI art. There's xbin files, which can store 8 6-bit custom colours, there's 24 bit ansi escape sequences that Pablo Draw uses, there's a more obvious, but incompatible, 24 bit and 256 colour implementations in x-term. I don't know much about MU* clients, so maybe you can educate me here, which I assume use another standard.

To incorporate all these standards, and inform the user as to which should be used in what circumstance is no minor feat, and PabloDraw was a cause of endless confusion for some users who wanted to use custom colours but couldn't save their file properly because of the lack of knowledge of which file format was most suitable for the job.

I don't particularly want to go down this rabbit hole because it would require a lot more work than I am prepared to invest, but thank you for your feedback anyway, and I'll keep your request in mind if I ever think of a simple and effective way of implementing custom palettes.
